client_id = "d1578d96-4a0d-4ac2-9390-48c6d9d50517"
client_secret = "Lue8Q~Q3AiBpMRTjo63VrOAc-DVfPX1WnglNxbvf"
tenant_id = "32c75521-fc9f-4e42-8f92-2460b43494d0"

excel_filename = "mvp_HR_KPI.xlsx"
table_name = "HR_data"
